### ISSUE TITLE
Please help me solve this error.

### ISSUE THREAD

**Issue by hemangjoshi37a** [hemangjoshi37a/generalML#1]
## Version : 
Kivy  : Latest
Python : 3.6
OS : Windows 7

## Code : 
```
< LoadDialog  >:
    name : "loadfile"
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)
```

## Error : 
```
  File "C:\Users\hj\main.kv", line 806, in <module>
    on_release: root.load(filechooser.path, filechooser.selection)

TypeError: 'NoneType' object is not callable
```
